//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTG
{
    public partial class KpiTargetSetup
    {
        protected global::System.Web.UI.WebControls.TextBox txtOnTrackMinimum;
        protected global::System.Web.UI.WebControls.TextBox txtAboveTargetMinimum;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Button btnSave;
    }
}